[package]
name = "bevy_type_registry"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = { path = "../bevy_app" }
bevy_ecs = { path = "../bevy_ecs" }
bevy_property = { path = "../bevy_property" }
serde = { version = "1", features = ["derive"] }