[package]
name = "bevy_sprite"
version = "0.1.0"
edition = "2018"
authors = ["Bevy Contributors <bevyengine@gmail.com>", "Carter Anderson <mcanders1@gmail.com>"]
description = "Provides sprite functionality for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT"
keywords = ["bevy"]

[dependencies]
bevy_app = { path = "../bevy_app" }
bevy_core = { path = "../bevy_core" }
bevy_ecs = { path = "../bevy_ecs" }
bevy_asset = { path = "../bevy_asset" }
bevy_type_registry = { path = "../bevy_type_registry" }
bevy_render = { path = "../bevy_render" }
bevy_transform = { path = "../bevy_transform" }

bevy_math = { path = "../bevy_math" }
rectangle-pack = "0.1"
thiserror = "1.0"
guillotiere = "0.5.2"