[package]
name = "bevy_winit"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies]
bevy_app = { path = "../bevy_app" }
bevy_input = { path = "../bevy_input" }
bevy_window = { path = "../bevy_window" }
legion = { path = "../bevy_legion" }

winit = { version = "0.22.2" }
glam = "0.8.7"
log = { version = "0.4", features = ["release_max_level_info"] }