[package]
name = "bevy_winit"
version = "0.1.0"
edition = "2018"
authors = ["Bevy Contributors <bevyengine@gmail.com>", "Carter Anderson <mcanders1@gmail.com>"]
description = "A winit window and input backend for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT"
keywords = ["bevy"]

[dependencies]
bevy_app = { path = "../bevy_app" }
bevy_ecs = { path = "../bevy_ecs" }
bevy_input = { path = "../bevy_input" }
bevy_window = { path = "../bevy_window" }

winit = { git = "https://github.com/rust-windowing/winit/", default-features = false, features = ["x11"] }
bevy_math = { path = "../bevy_math" }
log = { version = "0.4", features = ["release_max_level_info"] }