[package]
name = "bevy_winit"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies]
bevy_app = { path = "../bevy_app" }
bevy_ecs = { path = "../bevy_ecs" }
bevy_input = { path = "../bevy_input" }
bevy_window = { path = "../bevy_window" }

winit = { git = "https://github.com/rust-windowing/winit/", default-features = false, features = ["x11"] }
bevy_math = { path = "../bevy_math" }
log = { version = "0.4", features = ["release_max_level_info"] }