[package]
name = "bevy_property"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
erased-serde = "0.3"
bevy_property_derive = { path = "bevy_property_derive" }
ron = { git = "https://github.com/ron-rs/ron", rev = "35355ba7eb495f07282162826c29873154c2fa14" }
glam = { version = "0.8.7", features = ["serde"] }
legion = { path = "../bevy_legion" }
smallvec = { version = "1.4", features = ["serde"] }