[package]
name = "bevy"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[features]
default = ["headless", "wgpu", "winit"]
headless = ["asset", "type_registry", "core", "derive", "diagnostic", "gltf", "input", "pbr", "property", "render", "scene", "text", "transform", "ui", "window"]
asset = ["bevy_asset"]
core = ["bevy_core"]
type_registry = ["bevy_type_registry"]
derive = ["bevy_derive"]
diagnostic = ["bevy_diagnostic"]
gltf = ["bevy_gltf"]
input = ["bevy_input"]
pbr = ["bevy_pbr"]
property = ["bevy_property"]
render = ["bevy_render"]
scene = ["bevy_scene"]
text = ["bevy_text"]
transform = ["bevy_transform"]
ui = ["bevy_ui"]
window = ["bevy_window"]
wgpu = ["bevy_wgpu"]
winit = ["bevy_winit"]
more-system-fns = ["legion/more-system-fns"]

[workspace]
members = [
    "crates/*",
    "examples/app/dynamic_plugin_loading/example_plugin"
]
exclude = [
    "crates/bevy_glam",
    "crates/bevy_legion"
]

[dependencies]
# bevy
bevy_app = { path = "crates/bevy_app" }
bevy_asset = { path = "crates/bevy_asset", optional = true }
bevy_type_registry = { path = "crates/bevy_type_registry", optional = true }
bevy_core = { path = "crates/bevy_core", optional = true }
bevy_derive = { path = "crates/bevy_derive", optional = true }
bevy_diagnostic = { path = "crates/bevy_diagnostic", optional = true }
bevy_gltf = { path = "crates/bevy_gltf", optional = true }
bevy_input = { path = "crates/bevy_input", optional = true }
bevy_pbr = { path = "crates/bevy_pbr", optional = true }
bevy_property = { path = "crates/bevy_property", optional = true }
bevy_render = { path = "crates/bevy_render", optional = true }
bevy_scene = { path = "crates/bevy_scene", optional = true }
bevy_transform = { path = "crates/bevy_transform", optional = true }
bevy_text = { path = "crates/bevy_text", optional = true }
bevy_ui = { path = "crates/bevy_ui", optional = true }
bevy_window = { path = "crates/bevy_window", optional = true }
bevy_wgpu = { path = "crates/bevy_wgpu", optional = true }
bevy_winit = { path = "crates/bevy_winit", optional = true }
legion = { path = "crates/bevy_legion" }
glam = { path = "crates/bevy_glam" }
# other
log = { version = "0.4", features = ["release_max_level_info"] }

[dev-dependencies]
rand = "0.7.2"
serde = { version = "1", features = ["derive"]}
ron = { git = "https://github.com/ron-rs/ron", rev = "b43c1074d517131fd0cfc1deb96e11f95d6f42d8" }
serde_json = "1.0"
env_logger = "0.7"

[profile.dev]
opt-level = 3

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[[example]]
name = "sprite"
path = "examples/2d/sprite.rs"

[[example]]
name = "load_model"
path = "examples/3d/load_model.rs"

[[example]]
name = "parenting"
path = "examples/3d/parenting.rs"

[[example]]
name = "3d_scene"
path = "examples/3d/3d_scene.rs"

[[example]]
name = "spawner"
path = "examples/3d/spawner.rs"

[[example]]
name = "texture"
path = "examples/3d/texture.rs"

[[example]]
name = "dynamic_plugin_loading"
path = "examples/app/dynamic_plugin_loading/main.rs"

[[example]]
name = "empty_defaults"
path = "examples/app/empty_defaults.rs"

[[example]]
name = "empty"
path = "examples/app/empty.rs"

[[example]]
name = "headless"
path = "examples/app/headless.rs"

[[example]]
name = "plugin"
path = "examples/app/plugin.rs"

[[example]]
name = "hot_asset_reloading"
path = "examples/asset/hot_asset_reloading.rs"

[[example]]
name = "asset_loading"
path = "examples/asset/asset_loading.rs"

[[example]]
name = "custom_diagnostic"
path = "examples/diagnostics/custom_diagnostic.rs"

[[example]]
name = "print_diagnostics"
path = "examples/diagnostics/print_diagnostics.rs"

[[example]]
name = "event"
path = "examples/ecs/event.rs"

[[example]]
name = "startup_system"
path = "examples/ecs/startup_system.rs"

[[example]]
name = "ecs_guide"
path = "examples/ecs/ecs_guide.rs"

[[example]]
name = "input_mouse"
path = "examples/input/input_mouse.rs"

[[example]]
name = "input_keyboard"
path = "examples/input/input_keyboard.rs"

[[example]]
name = "load_scene"
path = "examples/scene/load_scene.rs"

[[example]]
name = "properties"
path = "examples/scene/properties.rs"

[[example]]
name = "shader_custom_material"
path = "examples/shader/shader_custom_material.rs"

[[example]]
name = "shader_defs"
path = "examples/shader/shader_defs.rs"

[[example]]
name = "text"
path = "examples/ui/text.rs"

[[example]]
name = "ui"
path = "examples/ui/ui.rs"

[[example]]
name = "ui_bench"
path = "examples/ui/ui_bench.rs"

[[example]]
name = "multiple_windows"
path = "examples/window/multiple_windows.rs"