[package]
name = "bevy_transform"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>", "Alec Thilenius <alec@thilenius.com>"]
edition = "2018"

license = "MIT"

[dependencies]
bevy_app = { path = "../bevy_app"}
bevy_ecs = { path = "../bevy_ecs"}
bevy_property = { path =  "../bevy_property" }
bevy_type_registry = { path =  "../bevy_type_registry" }
bevy_math = { path = "../bevy_math" }
log = "0.4"
smallvec = { version = "1.4", features = ["serde"] }

