[package]
name = "bevy_app"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies]
bevy_derive = { path = "../bevy_derive" }
bevy_ecs = { path = "../bevy_ecs" }
libloading = "0.6"
log = { version = "0.4", features = ["release_max_level_info"] }
serde = { version = "1.0", features = ["derive"]}