[package]
name = "bevy_core"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies]
bevy_app = { path = "../bevy_app" }
bevy_derive = { path = "../bevy_derive" }
bevy_ecs = { path = "../bevy_ecs" }
bevy_property = { path = "../bevy_property" }
bevy_type_registry = { path = "../bevy_type_registry" }
glam = "0.8.7"