[package]
name = "bevy_ecs"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
profiler = []

[dependencies]
hecs = { path = "hecs", features = ["macros", "serialize"] }
rand = "0.7.2"
rayon = "1.3"