[package]
name = "bevy_window"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies]
bevy_app = { path = "../bevy_app" }
legion = { path = "../bevy_legion" }
glam = "0.8.7"
uuid = { version = "0.8", features = ["v4", "serde"] }