[package]
name = "legion"
version = "0.2.4"
description = "High performance entity component system (ECS) library"
authors = ["Thomas Gillen <thomas.gillen@googlemail.com>"]
repository = "https://github.com/TomGillen/legion"
keywords = ["ecs", "game"]
categories = ["game-engines", "data-structures"]
readme = "readme.md"
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "TomGillen/legion", branch = "master" }

[features]
default = ["par-iter", "par-schedule", "ffi"]
par-iter = ["legion-core/par-iter", "legion-systems/par-iter"]
par-schedule = ["legion-systems/par-schedule"]
log = ["tracing/log", "tracing/log-always"]
ffi = ["legion-core/ffi"]
serialize = ["legion-core/serialize"]
metrics = ["legion-core/metrics"]
more-system-fns = ["legion-systems/more-system-fns"]

# [workspace]
# members = [
#     "legion_core",
#     "legion_systems",
# ]

[dependencies]
legion-core = { path = "legion_core", version = "0.2.4", default-features = false }
legion-systems = { path = "legion_systems", version = "0.2.4", default-features = false }

[dev-dependencies]
criterion = "0.3"
cgmath = "0.17"
tracing-subscriber = "0.2"
erased-serde = "0.3"
serde = { version = "1", features = ["derive"]}
uuid = { version = "0.8", features = ["v4", "serde"] }
tracing = "0.1"
itertools = "0.9"
rayon = "1.2"
crossbeam-channel = "0.4.2"

[[bench]]
name = "benchmarks"
harness = false

[[bench]]
name = "parallel_query"
harness = false

[[bench]]
name = "transform"
harness = false

[[bench]]
name = "insertion"
harness = false
