[package]
name = "bevy_diagnostic"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[features]
profiler = []

[dependencies]
bevy_app = { path = "../bevy_app" }
bevy_core = { path = "../bevy_core" }
bevy_ecs = { path = "../bevy_ecs" }
uuid = { version = "0.8", features = ["v4", "serde"] }
