[package]
name = "bevy_input"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies]
bevy_app = { path = "../bevy_app" }
bevy_ecs = { path = "../bevy_ecs" }
glam = "0.8.7"
