[package]
name = "bevy_wgpu"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[features]
default = ["bevy_winit"]

[dependencies]
# bevy
bevy_app = { path = "../bevy_app" }
bevy_asset = { path = "../bevy_asset" }
bevy_core = { path = "../bevy_core" }
bevy_diagnostic = { path = "../bevy_diagnostic" }
bevy_render = { path = "../bevy_render" }
bevy_window = { path = "../bevy_window" }
bevy_winit = { path = "../bevy_winit", optional = true }
legion = { path = "../bevy_legion" }

# render
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "7b866b1a1b72d4ecb7a63e11fbc8f521fe9eb363" }
# wgpu = { version = "0.5.0" }

pollster = "0.2.0"
log = { version = "0.4", features = ["release_max_level_info"] }
crossbeam-channel = "0.4.2"
crossbeam-utils = "0.7.2"