[package]
name = "bevy_wgpu"
version = "0.1.0"
edition = "2018"
authors = ["Bevy Contributors <bevyengine@gmail.com>", "Carter Anderson <mcanders1@gmail.com>"]
description = "A wgpu render backend for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT"
keywords = ["bevy"]

[features]
default = ["bevy_winit"]

[dependencies]
# bevy
bevy_app = { path = "../bevy_app" }
bevy_asset = { path = "../bevy_asset" }
bevy_core = { path = "../bevy_core" }
bevy_diagnostic = { path = "../bevy_diagnostic" }
bevy_ecs = { path = "../bevy_ecs" }
bevy_render = { path = "../bevy_render" }
bevy_window = { path = "../bevy_window" }
bevy_winit = { path = "../bevy_winit", optional = true }

# render
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "8c4d814607a303458ad9453da59dfc3a9951d7a3" }

pollster = "0.2.0"
log = { version = "0.4", features = ["release_max_level_info"] }
crossbeam-channel = "0.4.2"
crossbeam-utils = "0.7.2"