[package]
name = "bevy_audio"
version = "0.1.0"
edition = "2018"
authors = ["Bevy Contributors <bevyengine@gmail.com>", "Carter Anderson <mcanders1@gmail.com>"]
description = "Provides audio functionality for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT"
keywords = ["bevy"]

[dependencies]
bevy_app = {path = "../bevy_app"}
bevy_asset = {path = "../bevy_asset"}
bevy_ecs = {path = "../bevy_ecs"}
anyhow = "1.0"
rodio = {version = "0.11", default-features = false, features = ["mp3"]}
