[package]
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"
name = "bevy_derive"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
Inflector = {version = "0.11.4", default-features = false}
proc-macro-crate = "0.1.4"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
