name: Rust

on:
  # NOTE: temporarily disabled because on-push currently uses up too many resources
  # push:
  #   branches: [master]
  schedule:
    - cron:  '0 21 * * *'
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install alsa
        run: sudo apt-get install libasound2-dev
      - name: Build
        run: cargo check
      - name: Run tests
        run: cargo test --workspace

